language: node_js
  node_js:
    - node
  cache:
    directories:
      - node_modules
  addons:
    browserstack:
      username: 'devdev39'
      access_key: 'zXKZDJiV4JBVv8sZt4xo'
      app_path: android/app/release/app-release.apk
      forcelocal: true
  script: 
    - yarn test
    - yarn testandroid-bs
