language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
before_script:
  - echo $BS_USERNAME
script: 
  - yarn test
  - yarn testandroid-bs
addons:
  browserstack:
    username: "$BS_USERNAME"
    access_key:
      secure: "ULv6y6Y9n6gZSAhidPdmuOQmaiJeGyKej/PkMR89rmqCgRavO0lnhPl6yhYAaxMXu9iaCkuTAwccwriewwl5X4JEYjFOcl2bUhiZyfadW1FmTI1jMiUuBHLMJYcEFhO0TWNnhcLbalWjGlrToDIrHWm5eypS5DJNfCTflivxe8yId8ISLeogo/k9WNzd8UfgsRK5ZM6qFwHeTvSwUYKvvzFK4FNp9DtGazG6V1i3RZnNJsmNMXQ+29ycNQgcEscWoMezdGWG4hkjyroGXoiLYU9rpo1XrBdEN6pFW2kq5d/YbjPJbVw+RB1BBRXHlV9aUN4hexjKHP+VSGmFIc1Ah8BYnFn/Ck21Yh52O5zS0TfMdRg/r0tbYl9uMS6PDm3gBcDRSRHSfeVF4SJM9XqzUj5fjO7GJ3Bf1fb/WDPllkdUg7KwQKydQhd0yEVd3akXHZIDTu2QOdYT/iaz5Mp6JJtqG/mYVV6iavwHwUQi6D9z9WRyAyZ6uBGdZwBYgL4cCn7OsunbqdaD6dDzWq9S71WUhCNzy+JUbOAQtW28kC342upoYf2qI1enYX+DB7saBYDc101TJ6N2pWxTw5M/NRytIUSWvaGxRyEraZ9v6ECQrKoMWms5oHjIb3mlVsh/242A393P4vwCCYFPk1P/kTmC5ZEV1Pud4tbGIekbaS8="
    app_path: android/app/release/app-release.apk
    forcelocal: true
before_deploy:
  # Set up git user name and tag this commit
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - export RELEASE_NAME=$TRAVIS_BRANCH Release $TRAVIS_TAG
deploy:
  provider: releases
    api_key: $GITHUB_TOKEN
    file: android/app/release/app-release.apk
    skip_cleanup: true
    name: $RELEASE_NAME
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(uat|master)$
      